image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Setting up AWS CLI"
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

  - command: echo "Welcome to Gitpod! AWS CLI and Docker are ready."
